# Generated by Django 4.1 on 2022-08-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(related_name='publicacion', to='publicacion.categoria'),
        ),
    ]
